# Generated by Django 3.2 on 2023-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230624_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_postal',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
