# Generated by Django 3.2 on 2023-06-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230624_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
