# Generated by Django 3.2 on 2023-06-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_stripe_event_id_order_stripe_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_invoice_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
